export const QUERY_SCHEDULE = 'AppointVisit/QUERY_SCHEDULE';
export const QUERY_SCHEDULE_SUCCESS = 'AppointVisit/QUERY_SCHEDULE_SUCCESS';
export const QUERY_SCHEDULE_FAILURE = 'AppointVisit/QUERY_SCHEDULE_FAILURE';

export const APPOINT_VISIT = 'AppointVisit/APPOINT_VISIT';
export const APPOINT_VISIT_SUCCESS = 'AppointVisit/APPOINT_VISIT_SUCCESS';
export const APPOINT_VISIT_FAILURE = 'AppointVisit/APPOINT_VISIT_FAILURE';

export const QUERY_DEPARTMENT = 'AppointVisit/QUERY_DEPARTMENT';
export const QUERY_DEPARTMENT_SUCCESS = 'AppointVisit/QUERY_DEPARTMENT_SUCCESS';
export const QUERY_DEPARTMENT_FAILURE = 'AppointVisit/QUERY_DEPARTMENT_FAILURE';

export const QUERY_PATIENT_RECORD = 'AppointVisit/QUERY_PATIENT_RECORD';
export const QUERY_PATIENT_RECORD_SUCCESS = 'AppointVisit/QUERY_PATIENT_RECORD_SUCCESS';
export const QUERY_PATIENT_RECORD_FAILURE = 'AppointVisit/QUERY_PATIENT_RECORD_FAILURE';
