
export const HTTP_SEND_FETCH_REQUESTED = "LOGIN/HTTP_SEND_FETCH_REQUESTED";
export const HTTP_SEND_FETCH_REQUESTED_SUCCEED = "LOGIN/HTTP_SEND_FETCH_REQUESTED_SUCCEED";
export const HTTP_SEND_FETCH_REQUESTED_ERROR = "LOGIN/HTTP_SEND_FETCH_REQUESTED_ERROR";
export const HTTP_SEND_FETCH_REQUESTED_FAILED = "LOGIN/HTTP_SEND_FETCH_REQUESTED_FAILED";

export const GET_USER_INFO = "LOGIN/GET_USER_INFO";
export const GET_USER_INFO_SUCCEED = "LOGIN/GET_USER_INFO_SUCCEED";
export const GET_USER_INFO_ERROR = "LOGIN/GET_USER_INFO_ERROR";
export const GET_USER_INFO_FAILED = "LOGIN/GET_USER_INFO_FAILED";

export const REGISTER = "LOGIN/REGISTER";
export const REGISTER_SUCCEED = "LOGIN/REGISTER_SUCCEED";
export const REGISTER_ERROR = "LOGIN/REGISTER_ERROR";
export const REGISTER_FAILED = "LOGIN/REGISTER_FAILED";

export const UPDATE_REDUCER = "LOGIN/UPDATE_REDUCER";