export const QUERY_VISIT_RECORD = 'VisitRecord/QUERY_VISIT_RECORD';
export const QUERY_VISIT_RECORD_SUCCESS = 'VisitRecord/QUERY_VISIT_RECORD_SUCCESS';
export const QUERY_VISIT_RECORD_FAILURE = 'VisitRecord/QUERY_VISIT_RECORD_FAILURE';

