export const QUERY_DOCTOR_SCHEDULE = 'DoctorSchedule/QUERY_DOCTOR_SCHEDULE';
export const QUERY_DOCTOR_SCHEDULE_SUCCESS = 'DoctorSchedule/QUERY_DOCTOR_SCHEDULE_SUCCESS';
export const QUERY_DOCTOR_SCHEDULE_FAILURE = 'DoctorSchedule/QUERY_DOCTOR_SCHEDULE_FAILURE';

export const START_VISIT = 'DoctorSchedule/START_VISIT';
export const START_VISIT_SUCCESS = 'DoctorSchedule/START_VISIT_SUCCESS';
export const START_VISIT_FAILURE = 'DoctorSchedule/START_VISIT_FAILURE';

export const RECORD_MEDICAL = 'DoctorSchedule/RECORD_MEDICAL';
export const RECORD_MEDICAL_SUCCESS = 'DoctorSchedule/RECORD_MEDICAL_SUCCESS';
export const RECORD_MEDICAL_FAILURE = 'DoctorSchedule/RECORD_MEDICAL_FAILURE';

export const REGISTER_MEDICAL = 'DoctorSchedule/REGISTER_MEDICAL';
export const REGISTER_MEDICAL_SUCCESS = 'DoctorSchedule/REGISTER_MEDICAL_SUCCESS';
export const REGISTER_MEDICAL_FAILURE = 'DoctorSchedule/REGISTER_MEDICAL_FAILURE';


