export const QUERY_DOCTOR_SCHEDULE = 'DoctorSchedule/QUERY_DOCTOR_SCHEDULE';
export const QUERY_DOCTOR_SCHEDULE_SUCCESS = 'DoctorSchedule/QUERY_DOCTOR_SCHEDULE_SUCCESS';
export const QUERY_DOCTOR_SCHEDULE_FAILURE = 'DoctorSchedule/QUERY_DOCTOR_SCHEDULE_FAILURE';

export const UPDATE_SCHEDULING = 'DoctorSchedule/UPDATE_SCHEDULING';
export const UPDATE_SCHEDULING_SUCCESS = 'DoctorSchedule/UPDATE_SCHEDULING_SUCCESS';
export const UPDATE_SCHEDULING_FAILURE = 'DoctorSchedule/UPDATE_SCHEDULING_FAILURE';

export const QUERY_PATIENT_RECORD = 'DoctorSchedule/QUERY_PATIENT_RECORD';
export const QUERY_PATIENT_RECORD_SUCCESS = 'DoctorSchedule/QUERY_PATIENT_RECORD_SUCCESS';
export const QUERY_PATIENT_RECORD_FAILURE = 'DoctorSchedule/QUERY_PATIENT_RECORD_FAILURE';


