export const QUERY_PATIENT_INFO = 'PatientInfo/QUERY_PATIENT_INFO';
export const QUERY_PATIENT_INFO_SUCCESS = 'PatientInfo/QUERY_PATIENT_INFO_SUCCESS';
export const QUERY_PATIENT_INFO_FAILURE = 'PatientInfo/QUERY_PATIENT_INFO_FAILURE';

export const UPDATE_PATIENT_INFO = 'PatientInfo/UPDATE_PATIENT_INFO';
export const UPDATE_PATIENT_INFO_SUCCESS = 'PatientInfo/UPDATE_PATIENT_INFO_SUCCESS';
export const UPDATE_PATIENT_INFO_FAILURE = 'PatientInfo/UPDATE_PATIENT_INFO_FAILURE';
